<?php
require('db.php');

$sql = "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Maruti Suzuki', 'Alto', 'Std', 294800, 3,  'FWD (Front Wheel Drive)', 'Front, Transverse', 35, 'Petrol', 'Hatchback', 28.4, 5, '48PS@6000rpm', '69Nm@3500rpm', 5, 'Manual', 378);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Maruti Suzuki', 'Celerio', 'Zxi', 490924, 3,  'FWD (Front Wheel Drive)', 'Front, Transverse', 35, 'Petrol', 'Hatchback', 23, 5, '68PS@6000rpm', '90Nm@3500rpm', 5, 'Manual', 235);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Maruti Suzuki', 'Swift', 'Ldi', 599000, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 37, 'Diesel', 'Hatchback', 26, 5, '75PS@4000rpm', '190Nm@2000rpm', 5, 'Manual', 268);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Maruti Suzuki', 'Ciaz', '1.3L Alpha Smart Hybrid', 1102689, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 43, 'Diesel', 'Sedan', 28.09, 5, '89Bhp@4000RPM', '200Nm@1750rpm', 5, 'Manual', 510);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Maruti Suzuki', 'WagonR', 'Lxi', 434000, 3,  'FWD (Front Wheel Drive)', 'Front, Transverse', 32, 'Petrol', 'Hatchback', 5.2, 5, '68PS@5500rpm', '90Nm@3500rpm', 5, 'Manual', 341);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Hyundai', 'Santro', 'Era Mt', 429990, 2,  'FWD (Front Wheel Drive)', 'Front, Transverse', 35, 'Petrol', 'Hatchback', 14.3, 5, '69PS@5500rpm', '99.04nm@4500RPM', 5, 'Manual', 510);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Hyundai', 'Aura', 'S 1.2 Diesel', 773800, 4,  'FWD (Front Wheel Drive)', 'Front, Longitudinal', 37, 'Diesel', 'Sedan', 18.4, 5, '75PS@4000rpm', '190NM@1750-2250RPM', 5, 'Manual', 285);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Hyundai', 'Venue', '1.0 Turbo Gdi Dct Sx Plus', 1115500, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 45, 'Petrol', 'SUV', 24, 5, '118@6000rpm', '172Nm@1500-4000rpm', 5, 'DCT', 350);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Hyundai', 'Verna', '1.4 Crdi E', 942867, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 45, 'Diesel', 'Sedan', 14, 5, '100PS@6000rpm', '133Nm@4000rpm', 5, 'Manual', 465);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Hyundai', 'Elantra', 'Sx', 1849000, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 50, 'Petrol', 'Sedan', 13.1, 5, '152PS@6200rpm', '196Nm@4000rpm', 5, 'Manual', 256);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Tata', 'Hexa', 'Xt 4X4', 1929417, 4,  'RWD (Rear Wheel Drive)', 'Front, Transverse', 60, 'Diesel', 'SUV', 14, 5, '156PS@4000rpm', '320Nm@1700-2700rpm', 6, 'Manual', 128);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Tata', 'Nano Genx', 'Xm', 272223, 2,  'RWD (Rear Wheel Drive)', 'Rear, Transverse', 24, 'Petrol', 'Hatchback', 23.6, 5, '38PS@5500rpm', '51Nm@4000rpm', 4, 'Manual', 110);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Tata', 'Nexon', 'Xz Plus Diesel Dual Tone', 1120000, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 44, 'Diesel', 'SUV', 23.97, 5, '110PS@3750RPM', '260Nm@1500-2750rpm', 5, 'Manual', 350);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Tata', 'Zest', 'Xm Diesel', 767317, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 44, 'Diesel', 'Sedan', 19.2, 5, '75PS@4000rpm', '190Nm@1750-3000rpm', 5, 'Manual', 390);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Tata', 'Tigor', 'Revotron Xm', 610000, 3,  'FWD (Front Wheel Drive)', 'Front, Transverse', 35, 'Petrol', 'Sedan', 24.12, 5, '86PS@6000rpm', '113Nm@3300rpm', 5, 'Manual', 419);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Kia', 'Seltos', 'Gtx 1.4', 1529000, 4,  'FWD (Front Wheel Drive)', 'Front, Longitudinal', 50, 'Petrol', 'SUV', 16.1, 5, '140PS@6000RPM', '242Nm@1500-3200rpm', 5, 'Manual', 433);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Kia', 'Carnival', 'Premium 8 Str', 2515000, 4,  'FWD (Front Wheel Drive)', 'Front, Longitudinal', 60, 'Diesel', 'MUV', 16.8, 5, '200PS@3800rpm', '440Nm@1750-2750rpm', 7, 'Automatic', 540);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Kia', 'Seltos', 'Hte 1.5', 989000, 4,  'FWD (Front Wheel Drive)', 'Front, Longitudinal', 60, 'Petrol', 'SUV', 16.8, 5, '115PS@6300rpm', '144Nm@4500 rpm', 5, 'Manual', 433);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Kia', 'Carnival', 'Prestige 7 Str', 2895000, 4,  'FWD (Front Wheel Drive)', 'Front, Longitudinal', 60, 'Diesel', 'MUV', 16.8, 5, '200PS@3800rpm', '440Nm@1750-2750rpm', 7, 'Automatic', 540);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Kia', 'Seltos', 'Htx 1.5', 1309000, 4,  'FWD (Front Wheel Drive)', 'Front, Longitudinal', 60, 'Petrol', 'SUV', 16.8, 5, '115PS@6300rpm', '144Nm@4500 rpm', 5, 'Manual', 433);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Mahindra', 'Verito Vibe', 'D2', 657628, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 50, 'Diesel', 'Hatchback', 18, 5, '65PS@4000rpm', '160Nm@2000rpm', 5, 'Manual', 330);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Mahindra', 'Alturas G4', '2Wd At', 2770150, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 70, 'Diesel', 'SUV', 12.35, 5, '178bhp@400rpm', '420Nm@1600-2600rpm', 5, 'Automatic', 330);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Mahindra', 'Kuv100 Nxt', 'K2 6Str', 488194, 3,  'FWD (Front Wheel Drive)', 'Front, Longitudinal', 35, 'Petrol', 'Hatchback', 15.5, 5, '82PS@5500RPM', '115NM@3500-3600RPM', 6, 'Manual', 243);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Mahindra', 'Xuv300', '1.5 W8', 1095129, 4,  'RWD (Rear Wheel Drive)', 'Front, Transverse', 42, 'Diesel', 'SUV', 20, 5, '115bhp@3750rpm', '300Nm@1500rpm', 5, 'Manual', 259);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Mahindra', 'Thar', 'Crde', 959860, 4,  '4WD', 'Front, Transverse', 60, 'Diesel', 'SUV', 13, 5, '105 Bhp@ 3800 rpm', '247Nm@1800-2000rpm', 6, 'Manual', 600);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Toyota', 'Glanza', 'V', 758200, 4,  'FWD (Front Wheel Drive)', 'Front, Longitudinal', 37, 'Petrol', 'Hatchback', 21.01, 5, '82PS@6000 rpm', '113Nm@4200 rpm', 5, 'Manual', 339);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Toyota', 'Platinum Etios', 'Gx', 689600, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 45, 'Petrol', 'Sedan', 13.6, 5, '90PS@5600rpm', '132Nm@3000rpm', 5, 'Manual', 592);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Toyota', 'Prius', 'Z8', 4509000, 4,  'FWD (Front Wheel Drive)', 'Front, Longitudinal', 43, 'Hybrid', 'Sedan', 15.1, 5, '98PS@5200rpm', '142Nm@3600rpm', 5, 'Automatic', 296);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Toyota', 'Camry', 'Hybrid', 3788000, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 50, 'Hybrid', 'Sedan', 23.2, 5, '178PS@5700rpm', '221Nm@3600-5200rpm', 5, 'Automatic', 296);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Toyota', 'Yaris', 'J', 940000, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 42, 'Petrol', 'Sedan', 17.1, 5, '107PS@6000rpm', '140Nm@4200rpm', 5, 'Manual', 476);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Renault', 'Triber', 'Rxe', 495000, 3,  'FWD (Front Wheel Drive)', 'Front, Transverse', 40, 'Petrol', 'MUV', 20.5, 5, '72PS@62050rpm', '96Nm@3500rpm', 7, 'Manual', 625);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Renault', 'Kwid', 'Rxe 0.8', 353290, 3,  'FWD (Front Wheel Drive)', 'Front, Transverse', 28, 'Petrol', 'Hatchback', 25.17, 5, '54PS@5678rpm', '72Nm@4386rpm', 5, 'Manual', 300);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Renault', 'Duster', 'Rxs Petrol', 919990, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 50, 'Petrol', 'SUV', 10, 5, '106PS@5600rpm', '142Nm@4000rpm', 5, 'Manual', 475);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Renault', 'Lodgy', 'Stepway Rxl 85Ps 8-Seater', 1053899, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 50, 'Diesel', 'MUV', 21.04, 5, '85PS@3750rpm', '200Nm@1900rpm', 8, 'Manual', 207);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Renault', 'Captur', 'Platine Petrol Dual Tone', 1199999, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 50, 'Petrol', 'SUV', 13.86, 5, '106PS@5600rpm', '142Nm@4000rpm', 5, 'Manual', 392);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Honda', 'City', 'Vx Mt Petrol', 1182000, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 40, 'Petrol', 'Sedan', 14.3, 5, '119PS@6600rpm', '145Nm@4600rpm', 5, 'Manual', 510);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Honda', 'Civic', '1.8 Vx Cvt', 1944900, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 47, 'Petrol', 'Sedan', 16.5, 5, '141PS@6500rpm', '174Nm@4300rpm', 5, 'Automatic', 430);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Honda', 'Brv', 'S Diesel', 1187900, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 42, 'Diesel', 'SUV', 16.2, 5, '100PS@3600rpm', '200Nm@1750rpm', 7, 'Manual', 223);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Honda', 'Amaze', 'Ace Edition Cvt Diesel', 979300, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 35, 'Diesel', 'Sedan', 27.4, 5, '100PS@3600rpm', '200Nm@1750rpm', 5, 'Automatic', 420);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Honda', 'Cr-V', '2Wd Diesel At', 3067001, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 57, 'Diesel', 'SUV', 19.5, 5, '120PS@4000RPM', '300NM@2000rpm', 7, 'Automatic', 150);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Ford', 'Freestyle', '1.5L Tdci Titanium', 790900, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 40, 'Diesel', 'Hatchback', 24.4, 5, '100PS@3750RPM', '215Nm@1750-3000RPM', 5, 'Manual', 257);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Ford', 'Aspire', '1.5 Tdci Ambiente', 699400, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 40, 'Diesel', 'Sedan', 26.1, 5, '100PS@3750RPM', '215Nm@1750-3000RPM', 5, 'Manual', 257);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Ford', 'Ecosport', '1.5L Ti-Vct Titanium Plus', 999900, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 52, 'Petrol', 'SUV', 23, 5, '123PS@6500rpm', '150Nm@4500rpm', 5, 'Manual', 352);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Ford', 'Endeavour', '2.2L 4X2 At Titanium Plus', 3233000, 4,  'RWD (Rear Wheel Drive)', 'Front, Transverse', 80, 'Diesel', 'SUV', 9.3, 5, '160PS@3200rpm', '385Nm@1600-2500rpm', 7, 'Automatic', 430);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('Ford', 'Figo', 'Ambiente 1.5 Tdci', 623000, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 40, 'Diesel', 'Hatchback', 17, 5, '100PS@3750RPM', '215Nm@1750-3000RPM', 5, 'Manual', 354);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('MG', 'Hector', '1.5L Sharp Dct', 1718000, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 44, 'Petrol', 'SUV', 10.3, 5, '141bhp', '250NM', 5, 'DCT', 278);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('MG', 'Zs Ev', 'Excite', 2088000, 4,  'RWD (Rear Wheel Drive)', 'Front, Longitudinal', 32, 'Electric', 'SUV', 17.41, 5, '142.76PS@3500rpm', '353Nm@5000rpm', 5, 'Automatic', 448);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('MG', 'Zs Ev', 'Exclusive', 2358000, 4,  'RWD (Rear Wheel Drive)', 'Front, Longitudinal', 32, 'Electric', 'SUV', 17.41, 5, '142.76PS@3500rpm', '353Nm@5000rpm', 5, 'Automatic', 448);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('MG', 'Hector', '2.0L Super', 1448000, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 32, 'Diesel', 'SUV', 17.41, 5, '168bhp', '350NM', 5, 'Manual', 278);";
$sql .= "INSERT INTO Specs (Make, Model, Variant, Ex_Showroom_Price, Cylinders, Drivetrain, Engine_Location, Fuel_Tank_Capacity, Fuel_Type, Body_Type, City_Mileage, Gears, Power, Torque, Seating_Capacity, Transmission, Boot_Space) VALUES ('MG', 'Hector', '2.0L Smart', 1588000, 4,  'FWD (Front Wheel Drive)', 'Front, Transverse', 32, 'Diesel', 'SUV', 17.41, 5, '168bhp', '350NM', 5, 'Manual', 278);";



if ($con->multi_query($sql) === TRUE) {
  echo "New Specs records created successfully<br>";
} else {
  echo "Error: " . $sql . "<br>" . $con->error;
}


//close connection
$con->close();
?>